import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import logo from "@/public/logo.png";
import Image from "next/image";
import Link from "next/link";

import Footer from "@/app/navigation";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center mb-4">
          <Image
            src={logo}
            width={300}
            height={300}
            alt="Description of the image"
            className="h-500 w-500"
          />
        </div>

        {/* Navigation bar */}

        <nav className="bg-gray-900 position:fixed ">
          <div className="flex justify-center items-center mx-48 py-4">
            <ul className="flex gap-16 font-medium bg-gray-900 text-xl justify-center items-center w-full">
              <li>
                <Link href="/home" className="hover:text-green-400 text-white">
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href="/constitution"
                  className="hover:text-green-400 text-white"
                >
                  Query
                </Link>
              </li>
              <li>
                <Link
                  href="/display"
                  className="hover:text-green-400 text-white"
                >
                  Nepal Constitution 2015
                </Link>
              </li>
            </ul>
          </div>
        </nav>

        <div className="shadow-md m-20  p-8 flex justify-center items-center rounded-2xl bg-gray-200 mt-16">
          {children}
        </div>
        <div className="container">
          <Footer />
        </div>
      </body>
    </html>
  );
}
