import React, { useState } from 'react';
import faqimage from "../assets/images/faq.png";

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleOpen = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const faqs = [
    {
      question: "How does the web app generate summaries from PDF articles?",
      answer: "The web app uses advanced AI algorithms to analyze the content of the provided PDF articles. The AI identifies key points, themes, and important information, then condenses this data into a concise summary. This allows users to quickly understand the main ideas of the article without reading the entire document."
    },
    {
      question: "Can the web app extract keywords from any type of PDF document?",
      answer: "Yes, the web app can extract keywords from a wide variety of PDF documents. Whether it's a research paper, a business report, or any other type of article, the AI analyzes the text to identify and extract relevant keywords that represent the core topics of the document."
    },
    {
      question: "How accurate are the summaries and keywords generated by the AI?",
      answer: "The accuracy of the summaries and keywords generated by the AI is generally high, thanks to sophisticated models by llmware. However, the accuracy can vary depending on the complexity and clarity of the original document. Users are encouraged to review the generated content to ensure it meets their needs."
    },
    {
      question: "Can I ask specific questions about the content of the PDF and get precise answers?",
      answer: "Absolutely! The web app includes a question-answer feature powered by AI. Users can ask specific questions about the content of the provided PDF, and the AI will analyze the document to provide precise and relevant answers. This feature is designed to help users quickly find specific information within lengthy articles."
    },
    {
      question: "Is there a limit to the size or length of the PDF files that can be uploaded?",
      answer: "There are some limitations on the size or length of PDF files that can be processed, depending on the web app's specific technical constraints. Generally, the app is designed to handle small article lengths."
    }
  ];
  

  return (
    <div className="bg-white text-black p-6 pb-14 mt-24">
      <div className="mx-10 md:mx-24">
        <h2 className="text-5xl font-bold mb-14 text-center">FREQUENTLY ASKED QUESTIONS</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="hidden md:flex justify-center items-center">
            <img src={faqimage} alt="FAQ" className="w-full h-auto md:max-w-md" />
          </div>
          <div>
            {faqs.map((faq, index) => (
              <div key={index} className="mb-4">
                <button
                  className="w-full text-left p-4 bg-gray-100 rounded-lg hover:bg-gray-200 focus:outline-none focus:ring focus:ring-gray-300"
                  onClick={() => toggleOpen(index)}
                >
                  <div className="flex justify-between items-center">
                    <span className="font-medium">{faq.question}</span>
                    <span className="text-2xl">{openIndex === index ? '-' : '+'}</span>
                  </div>
                </button>
                {openIndex === index && (
                  <div className="p-4 bg-gray-200 mt-2 rounded-lg">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>

        </div>
      </div>
    </div>
  );
};

export default FAQ;