# Generated by Django 5.0.6 on 2024-05-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_has_joined_group_projectgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApplyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_interested', models.TextField()),
                ('relevant_skills', models.TextField()),
                ('how_to_contribute', models.TextField()),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectgroup')),
            ],
        ),
    ]
