# Generated by Django 5.0.6 on 2024-05-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectapplydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplydetail',
            name='project_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.projectgroup'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='applied_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
