# Generated by Django 5.0.1 on 2024-05-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_projectapplydetail_project_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
