# Generated by Django 5.0.6 on 2024-05-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_application_selected',
            field=models.BooleanField(default=False),
        ),
    ]
