
import React, { useState } from 'react';
import faqimage from "../assets/images/faq.png";

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleOpen = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const faqs = [
    {
      question: "What is ArticleInsight?",
      answer: "ArticleInsight is an AI-powered tool that provides summaries, generates tags, analyzes sentiment, categorizes articles, and answers questions about the content."
    },
    {
      question: "How does ArticleInsight generate summaries?",
      answer: "ArticleInsight uses advanced AI models from LLMWare to analyze the content and produce concise and comprehensive summaries."
    },
    {
      question: "What kind of tags does ArticleInsight generate?",
      answer: "ArticleInsight generates relevant and contextual tags that help categorize and enhance the discoverability of your articles."
    },
    {
      question: "How does sentiment analysis work?",
      answer: "ArticleInsight analyzes the comments and feedback on your articles to determine the overall sentiment, whether positive, negative, or neutral."
    },
    {
      question: "Can ArticleInsight answer questions about the article?",
      answer: "Yes, you can ask specific questions about the article, and ArticleInsight will provide accurate and insightful answers generated by its advanced AI models."
    }
  ];

  return (
    <div className="bg-black text-white p-6 pb-14 mt-24">
      <div className="mx-10 md:mx-24">
        <h2 className="text-5xl font-bold mb-14 text-center">FREQUENTLY ASKED QUESTIONS</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h3 className='text-4xl font-bold mb-5'>Have questions?</h3>
            <h3 className='text-4xl font-bold mb-8'>Get your <span className='text-yellow-300'>answers!</span></h3>
            {faqs.map((faq, index) => (
              <div key={index} className="mb-4">
                <button
                  className="w-full text-left p-4 bg-gray-800 rounded-lg hover:bg-gray-700 focus:outline-none focus:ring focus:ring-gray-600"
                  onClick={() => toggleOpen(index)}
                >
                  <div className="flex justify-between items-center">
                    <span className="font-medium">{faq.question}</span>
                    <span className="text-2xl">{openIndex === index ? '-' : '+'}</span>
                  </div>
                </button>
                {openIndex === index && (
                  <div className="p-4 bg-gray-700 mt-2 rounded-lg">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
          <div className="hidden md:flex justify-center items-center">
            <img src={faqimage} alt="FAQ" className="w-full h-auto md:max-w-md" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default FAQ;
